namespace Java_Corruptor;

public class Constants
{
    public const int Ldc_W = 19;
    public const int Ldc_2W = 20;
    public const int Iload_0 = 26;
    public const int Iload_1 = 27;
    public const int Iload_2 = 28;
    public const int Iload_3 = 29;
    public const int Lload_0 = 30;
    public const int Lload_1 = 31;
    public const int Lload_2 = 32;
    public const int Lload_3 = 33;
    public const int Fload_0 = 34;
    public const int Fload_1 = 35;
    public const int Fload_2 = 36;
    public const int Fload_3 = 37;
    public const int Dload_0 = 38;
    public const int Dload_1 = 39;
    public const int Dload_2 = 40;
    public const int Dload_3 = 41;
    public const int Aload_0 = 42;
    public const int Aload_1 = 43;
    public const int Aload_2 = 44;
    public const int Aload_3 = 45;
    public const int Istore_0 = 59;
    public const int Istore_1 = 60;
    public const int Istore_2 = 61;
    public const int Istore_3 = 62;
    public const int Lstore_0 = 63;
    public const int Lstore_1 = 64;
    public const int Lstore_2 = 65;
    public const int Lstore_3 = 66;
    public const int Fstore_0 = 67;
    public const int Fstore_1 = 68;
    public const int Fstore_2 = 69;
    public const int Fstore_3 = 70;
    public const int Dstore_0 = 71;
    public const int Dstore_1 = 72;
    public const int Dstore_2 = 73;
    public const int Dstore_3 = 74;
    public const int Astore_0 = 75;
    public const int Astore_1 = 76;
    public const int Astore_2 = 77;
    public const int Astore_3 = 78;
    public const int Wide = 196;
    public const int Goto_W = 200;
    public const int Jsr_W = 201;
}